name: Windows (Google Remote Desktop)

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter Google Remote Desktop (Windows (PowerShell)) code'
        required: true
      computername:
        description: 'Computer Name'
        default: 'ZVM'
        required: true
      pincode:
        description: 'Six digit Pin'
        default: '12345678'
        required: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./GRDP-Setup.ps1 ${{ env.ComputerName }}
    - name: Starting Google Remote Desktop
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive.
      shell: bash
      run: sh Files/t.bat
